-- Schema source of truth: versioned migration (do not paste this file into the SQL editor as primary deploy).
-- Migration: supabase/migrations/20260418003000_add_app_settings_dashboard_settings.sql
-- Apply: `supabase db push` with a linked project, or your migration pipeline.
