-- Schema source of truth: versioned migration (do not paste this file into the SQL editor as primary deploy).
-- Migration: supabase/migrations/20260301106000_add_invoice_stripe_fields.sql
-- Apply: `supabase db push` with a linked project, or your migration pipeline.
