-- Schema source of truth: versioned migration (do not paste this file into the SQL editor as primary deploy).
-- Migration: supabase/migrations/20260301102000_fix_advisor_missing_tables.sql
-- Apply: `supabase db push` with a linked project, or your migration pipeline.
