-- Superseded by versioned migration (onboarding wizard + RPCs). Do not run this file as primary deploy.
-- Migration: supabase/migrations/20260417120000_onboarding_wizard_and_org_rpcs.sql
-- Apply: `supabase db push` with a linked project.
