-- Schema source of truth: versioned migration (do not paste this file into the SQL editor as primary deploy).
-- Migration: supabase/migrations/20260418007000_optional_vault_encryption_notes.sql
-- Apply: `supabase db push` with a linked project, or your migration pipeline.
