-- Schema source of truth: versioned migration (do not paste this file into the SQL editor as primary deploy).
-- Migration: supabase/migrations/20260418000000_org_rpcs_onboarding_select.sql
-- Apply: `supabase db push` with a linked project, or your migration pipeline.
