-- Schema source of truth: versioned migration (do not paste this file into the SQL editor as primary deploy).
-- Migration: supabase/migrations/20260301112000_organization_members_manage.sql
-- Apply: `supabase db push` with a linked project, or your migration pipeline.
